[tool.poetry]
name = "gachiniii"
version = "0.1.0"
description = "IwataGumi Discord Bot"
authors = ["IwataGumi Member"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
